function [StationCategory,Station,StationName,KatakanaName,Lat,Lon,LatDegree,LatMinute,LonDegree,LonMinute,Elevation,Precipitation,Wind,Teperature,Sunshine,Snowfall,VarName17,VarName18,VarName19,VarName20,Note1,Note2] = importfile(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [STATIONCATEGORY,STATION,STATIONNAME,KATAKANANAME,LAT,LON,LATDEGREE,LATMINUTE,LONDEGREE,LONMINUTE,ELEVATION,PRECIPITATION,WIND,TEPERATURE,SUNSHINE,SNOWFALL,VARNAME17,VARNAME18,VARNAME19,VARNAME20,NOTE1,NOTE2]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [STATIONCATEGORY,STATION,STATIONNAME,KATAKANANAME,LAT,LON,LATDEGREE,LATMINUTE,LONDEGREE,LONMINUTE,ELEVATION,PRECIPITATION,WIND,TEPERATURE,SUNSHINE,SNOWFALL,VARNAME17,VARNAME18,VARNAME19,VARNAME20,NOTE1,NOTE2]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [StationCategory,Station,StationName,KatakanaName,Lat,Lon,LatDegree,LatMinute,LonDegree,LonMinute,Elevation,Precipitation,Wind,Teperature,Sunshine,Snowfall,VarName17,VarName18,VarName19,VarName20,Note1,Note2] = importfile('obs_stations_UTF8.csv',3, 3324);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2019/07/17 14:11:15

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 3;
    endRow = inf;
end

%% Read columns of data as strings:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r','n','UTF-8');
% Skip the BOM (Byte Order Mark).
fseek(fileID, 3, 'bof');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric strings to numbers.
% Replace non-numeric strings with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = dataArray{col};
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[2,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,21,22]
    % Converts strings in the input cell array to numbers. Replaced non-numeric
    % strings with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1);
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData{row}, regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if any(numbers==',');
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'));
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric strings to numbers.
            if ~invalidThousandsSeparator;
                numbers = textscan(strrep(numbers, ',', ''), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch me
        end
    end
end


%% Split data into numeric and cell columns.
rawNumericColumns = raw(:, [2,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,21,22]);
rawCellColumns = raw(:, [1,3,4,20]);


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),rawNumericColumns); % Find non-numeric cells
rawNumericColumns(R) = {NaN}; % Replace non-numeric cells

%% Allocate imported array to column variable names
StationCategory = rawCellColumns(:, 1);
Station = cell2mat(rawNumericColumns(:, 1));
StationName = rawCellColumns(:, 2);
KatakanaName = rawCellColumns(:, 3);
Lat = cell2mat(rawNumericColumns(:, 2));
Lon = cell2mat(rawNumericColumns(:, 3));
LatDegree = cell2mat(rawNumericColumns(:, 4));
LatMinute = cell2mat(rawNumericColumns(:, 5));
LonDegree = cell2mat(rawNumericColumns(:, 6));
LonMinute = cell2mat(rawNumericColumns(:, 7));
Elevation = cell2mat(rawNumericColumns(:, 8));
Precipitation = cell2mat(rawNumericColumns(:, 9));
Wind = cell2mat(rawNumericColumns(:, 10));
Teperature = cell2mat(rawNumericColumns(:, 11));
Sunshine = cell2mat(rawNumericColumns(:, 12));
Snowfall = cell2mat(rawNumericColumns(:, 13));
VarName17 = cell2mat(rawNumericColumns(:, 14));
VarName18 = cell2mat(rawNumericColumns(:, 15));
VarName19 = cell2mat(rawNumericColumns(:, 16));
VarName20 = rawCellColumns(:, 4);
Note1 = cell2mat(rawNumericColumns(:, 17));
Note2 = cell2mat(rawNumericColumns(:, 18));


